### ISSUE TITLE
_color_params: unbound variable

### ISSUE THREAD

**Issue by romanhuba** [chadj2/biw-tools#1]
Hi,

I am getting this error when I press down arrow, any idea why this happens?

Im running Ubuntu-18.04 in WSL2 in Windows Terminal (Preview).

```bash
/home/roman/bash-ui-master/src/bui-theme-mgr.sh: line 145: _color_params: unbound variable





PANIC Failure at (main:1):
=> local -a _color_params=($_color_params)

Call stack:
1 main /home/roman/bash-ui-master/src/bui-main.sh
```

Thanks!

**Comment by chadj2** [comment]
There was an issue with changes to bash. I have this working on bash 5.0.11. Please re-test.
